name: Notify Discord on Deploy

on:
  workflow_run:
    workflows: ["Manual Deploy to Cloud Run", "Auto Deploy on Push to Master"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
            STATUS="✅ Deployment zakończony sukcesem!"
          else
            STATUS="❌ Deployment zakończył się błędem!"
          fi

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"**${{ github.workflow }}**\n$STATUS\nRepo: ${{ github.repository }}\nLink: https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}\"}" \
            $DISCORD_WEBHOOK
